from langchain_deepseek import ChatDeepSeek
from langchain_openai import OpenAIEmbeddings

from app.core.config import settings
from app.core.logger import logger



_global_embeddings = None
_global_llm = None

def get_embeddings():
    global _global_embeddings
    if _global_embeddings is None:
        logger.info('Initializing embedding API client...')

        api_key = settings.EMBEDDING_API_KEY or settings.LLM_API_KEY
        if not api_key:
            raise ValueError("EMBEDDING_API_KEY (or LLM_API_KEY) must be set for embedding API calls.")

        _global_embeddings = OpenAIEmbeddings(
            model=settings.EMBEDDING_MODEL,
            api_key=api_key,
            base_url=settings.EMBEDDING_BASE_URL,
            dimensions=settings.EMBEDDING_DIMENSIONS,
            # DashScope embedding endpoint limits input batch size to <= 10.
            chunk_size=10,
            # OpenAI-compatible providers (e.g. DashScope) may reject token-id
            # array input generated by langchain's len-safe path.
            # We pass plain string batches directly.
            check_embedding_ctx_length=False,
        )
    return _global_embeddings


def get_llm():
    global _global_llm
    if _global_llm is None:
        logger.info('Initializing LLM client...')
        _global_llm = ChatDeepSeek(model=settings.LLM_MODEL, api_key=settings.LLM_API_KEY, streaming=True)
    return _global_llm
