global:
  resolve_timeout: 5m


route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'sre-agent-webhook'

receivers:
- name: 'sre-agent-webhook'
  webhook_configs:
  - url: 'http://host.docker.internal:8000/webhook/alertmanager'
    send_resolved: false